### ISSUE TITLE
项目还会更新吗？

### ISSUE THREAD

**Issue by zgd716** [EcustBobo/OwnthinkQ-A#1]

**Comment by EcustBobo** [comment]
最近一段时间不会更新



自己的路自己走！


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EcustBobo/OwnthinkQ-A"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月25日(星期四) 上午9:46
收件人:&nbsp;"EcustBobo/OwnthinkQ-A"<OwnthinkQ-A@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[EcustBobo/OwnthinkQ-A] 项目还会更新吗？ (#1)
